/product/index:
  get:
    summary: 商品列表
    description: 商品列表
    tags:
      - 商品
    parameters:
      - name: id
        in: query
        description: 商品编号
        required: false
        type: integer
      - name: page_size
        in: query
        description: 页面大小
        required: false
        type: integer
      - name: page
        in: query
        description: 页面编号
        required: false
        type: integer
      - name: name
        in: query
        description: 商品名称
        required: false
        type: string
      - name: category_id
        in: query
        description: 商品分类
        required: false
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/add:
  post:
    summary: 添加商品
    description: 添加商品
    tags:
      - 商品
    parameters:
      - name: category_id
        in: formData
        description: 商品分类
        required: true
        type: integer
      - name: kind_id
        in: formData
        description: 商品类型
        required: true
        type: integer
      - name: name
        in: formData
        description: 商品名称
        required: true
        type: string
      - name: short_description
        in: formData
        description: 商品简介
        required: true
        type: string
      - name: unit
        in: formData
        description: 商品单位
        required: true
        type: integer
      - name: images
        in: formData
        description: 商品轮播图
        required: true
        type: string
      - name: spec_type
        in: formData
        description: 商品规格种类
        required: true
        type: integer
      - name: spec
        in: formData
        description: 商品规格
        required: true
        type: string
      - name: status
        in: formData
        description: 商品状态
        required: true
        type: integer
      - name: tags
        in: formData
        description: 商品标签
        required: true
        type: string
      - name: param
        in: formData
        description: 商品参数
        required: true
        type: string
      - name: description
        in: formData
        description: 商品描述
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/edit:
  post:
    summary: 编辑商品
    description: 编辑商品
    tags:
      - 商品
    parameters:
      - name: id
        in: formData
        description: 商品编号
        required: true
        type: integer
      - name: category_id
        in: formData
        description: 商品分类
        required: true
        type: integer
      - name: kind_id
        in: formData
        description: 商品类型
        required: true
        type: integer
      - name: name
        in: formData
        description: 商品名称
        required: true
        type: string
      - name: short_description
        in: formData
        description: 商品简介
        required: true
        type: string
      - name: unit
        in: formData
        description: 商品单位
        required: true
        type: integer
      - name: images
        in: formData
        description: 商品轮播图
        required: true
        type: string
      - name: spec_type
        in: formData
        description: 商品规格种类
        required: true
        type: integer
      - name: spec
        in: formData
        description: 商品规格
        required: true
        type: string
      - name: status
        in: formData
        description: 商品状态
        required: true
        type: integer
      - name: tags
        in: formData
        description: 商品标签
        required: true
        type: string
      - name: param
        in: formData
        description: 商品参数
        required: true
        type: string
      - name: description
        in: formData
        description: 商品描述
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/delete:
  post:
    summary: 删除商品
    description: 删除商品
    tags:
      - 商品
    parameters:
      - name: id
        in: formData
        description: 商品编号
        required: true
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'
