/product-spec/index:
  get:
    summary: 商品规格列表
    description: 商品规格列表
    tags:
      - 商品规格
    parameters:
      - name: id
        in: query
        description: 编号
        required: false
        type: integer
      - name: spec_name
        in: query
        description: 规格名称
        required: false
        type: string
      - name: page_size
        in: query
        description: 页面大小
        required: false
        type: integer
      - name: page
        in: query
        description: 页面编号
        required: false
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product-spec/add:
  post:
    summary: 添加商品规格
    description: 添加商品规格
    tags:
      - 商品规格
    parameters:
      - name: name
        in: formData
        description: 商品规格名称
        required: true
        type: string
      - name: sort
        in: formData
        description: 商品规格排序
        required: true
        type: integer
      - name: values
        in: formData
        description: 商品规格值(支持中、英、数字|多个值以,英文逗号隔开)
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product-spec/edit:
  post:
    summary: 编辑商品规格
    description: 编辑商品规格
    tags:
      - 商品规格
    parameters:
      - name: id
        in: formData
        description: 商品规格编号
        required: true
        type: integer
      - name: name
        in: formData
        description: 商品规格名称
        required: true
        type: string
      - name: sort
        in: formData
        description: 商品规格排序
        required: true
        type: integer
      - name: values
        in: formData
        description: 商品规格值(支持中、英、数字|多个值以,英文逗号隔开)
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product-spec/delete:
  post:
    summary: 删除商品规格
    description: 获取商品规格
    tags:
      - 商品规格
    parameters:
      - name: id
        in: formData
        description: 商品规格编号
        required: true
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product-spec/bindable-specs:
  get:
    summary: 获取可被绑定类型的规格列表
    description: 获取可被绑定类型的规格列表,无分页，支持模糊匹配名称
    tags:
      - 商品规格
    parameters:
      - name: name
        in: query
        description: 商品规格名称
        required: false
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'
