/product/index:
  get:
    summary: 商品列表
    description: 商品列表
    tags:
      - 商品
    parameters:
      - name: id
        in: query
        description: 商品编号
        required: false
        type: integer
      - name: page_size
        in: query
        description: 页面大小
        required: false
        type: integer
      - name: page
        in: query
        description: 页面编号
        required: false
        type: integer
      - name: name
        in: query
        description: 商品名称
        required: false
        type: string
      - name: category_id
        in: query
        description: 商品分类
        required: false
        type: integer
      - name: status
        in: query
        description: 商品状态(1下架|2上架)
        required: false
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/add:
  post:
    summary: 添加商品
    description: 添加商品
    tags:
      - 商品
    parameters:
      - name: category_id
        in: formData
        description: 商品分类
        required: true
        type: integer
      - name: kind_id
        in: formData
        description: 商品类型
        required: true
        type: integer
      - name: name
        in: formData
        description: 商品名称
        required: true
        type: string
      - name: short_description
        in: formData
        description: 商品简介(中、英、数字)长度1-50
        required: true
        type: string
      - name: unit
        in: formData
        description: 商品单位(中、英、数字)
        required: true
        type: integer
      - name: images
        in: formData
        description: 商品轮播图(支持多个已英文逗号隔开,英、数字)
        required: true
        type: string
      - name: spec_type
        in: formData
        description: 商品规格种类(1单规格|2多规格)
        required: true
        type: integer
      - name: spec
        in: formData
        description: 商品规格(json 数组对象[{image:string,"price":double,"old_price":double,"cost_price":double,"stock":integer,"sku":string,"weight":double,"volume":double,"spec_value_id":[],"product_spec_id":integer}])
        required: true
        type: string
      - name: status
        in: formData
        description: 商品状态(1下架|2上架)
        required: true
        type: integer
      - name: tags
        in: formData
        description: 商品标签(传json数组，数组中值为数字)
        required: false
        type: string
      - name: param
        in: formData
        description: 商品参数(json数组对象[{"param_id":integer,"value":string}])
        required: true
        type: string
      - name: description
        in: formData
        description: 商品描述(中文|英文|数字[{"images":"","text":""}])
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/edit:
  post:
    summary: 编辑商品
    description: 编辑商品
    tags:
      - 商品
    parameters:
      - name: id
        in: formData
        description: 商品编号
        required: true
        type: integer
      - name: category_id
        in: formData
        description: 商品分类
        required: true
        type: integer
      - name: kind_id
        in: formData
        description: 商品类型
        required: true
        type: integer
      - name: name
        in: formData
        description: 商品名称
        required: true
        type: string
      - name: short_description
        in: formData
        description: 商品简介(中、英、数字)长度1-50
        required: true
        type: string
      - name: unit
        in: formData
        description: 商品单位(中、英、数字)
        required: true
        type: integer
      - name: images
        in: formData
        description: 商品轮播图(支持多个以英文逗号隔开,英、数字)
        required: true
        type: string
      - name: spec_type
        in: formData
        description: 商品规格种类(1单规格|2多规格)
        required: true
        type: integer
      - name: spec
        in: formData
        description: 商品规格(json 数组对象[{image:string,"price":double,"old_price":double,"cost_price":double,"stock":integer,"sku":string,"weight":double,"volume":double,"spec_value_id":[],"product_spec_id":integer}])
        required: true
        type: string
      - name: status
        in: formData
        description: 商品状态(1下架|2上架)
        required: true
        type: integer
      - name: tags
        in: formData
        description: 商品标签(传json数组，数组中值为数字)
        required: true
        type: string
      - name: param
        in: formData
        description: 商品参数(json数组对象[{"param_id":integer,"value":string}])
        required: true
        type: string
      - name: description
        in: formData
        description: 商品描述(中文|英文|数字[{"images":"","text":""}])
        required: true
        type: string
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'

/product/delete:
  post:
    summary: 删除商品
    description: 删除商品
    tags:
      - 商品
    parameters:
      - name: id
        in: formData
        description: 商品编号
        required: true
        type: integer
    responses:
      200:
        description: 成功
        schema:
          $ref: '#/definitions/resp'
